@baseUrl = http://localhost:3000

###
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "username": "john",
  "password": "1234"
}

###
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "username": "john",
  "password": "1234"
}

## 생성된 토큰을 board 생성할 때 같이 넣어준다.

###