@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/boards

###
POST {{baseUrl}}/boards
Content-Type: application/json
Authorization: Bearer {token}

{
  "title": "Board 1",
  "description": "Description 1"
}
